# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SongDemonFramework' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SongDemonFramework
  pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'
end
